name: code-formatter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  format-code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: ministryofjustice/github-actions/code-formatter@v18.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
